name: Google Chat Integration

on:
  workflow_dispatch:

jobs:
  chat-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Step that may fail
      run: exit 1
        

    - name: Notify Google Chat on failure
      if: ${{ failure() }}
      run: |
        JOB_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        TEXT="🚨🚨 *Android Firebase Distribution failed!* 🚨🚨\nPlease, check the <${JOB_URL}|failed run> for more details."
        curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"${TEXT}\"}" \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
