name: Android Firebase distribution

on:
  workflow_dispatch:


jobs:
  char-integration:
    runs-on: ubuntu-latest

    steps:
    - name: Step that may fail
      run: exit 1
        

    - name: Notify Google Chat on failure
      if: ${{ failure() }}
      run: |
        JOB_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        MESSAGE="🚨Android Firebase Distribution workflow failed! Check details here: ${JOB_URL}"
        curl -X POST -H "Content-Type: application/json" \
          -d '{"text": \"${MESSAGE}\"}' \
          ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
